# Generated by Django 3.2.4 on 2022-10-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='lesson',
            field=models.IntegerField(default=0, verbose_name='第几节'),
            preserve_default=False,
        ),
    ]
