# Generated by Django 3.2.4 on 2022-10-03 13:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_courselesson_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='brief',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=2048, null=True, verbose_name='课程概述'),
        ),
    ]
