# Generated by Django 3.2.4 on 2022-09-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220930_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wxchat',
            field=models.CharField(blank=True, default=True, max_length=64, verbose_name='微信号'),
        ),
    ]
